---
- name: set gemrc
  copy: src=gemrc dest=/home/{{ deploy_user }}/.gemrc owner={{ deploy_user}} group={{ deploy_user }} mode=0644

- name: install bundler
  shell: RBENV_ROOT={{ rbenv_root }} rbenv exec gem install bundler --no-ri --no-rdoc
