default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  ctype: en_US.utf8
  collation: en_US.utf8
  template: template0
  pool: 5
  username: vagrant
  password: vagrant

development:
  <<: *default
  database: simple_cms_development

test:
  <<: *default
  database: simple_cms_test
